# Generated by Django 4.0.1 on 2022-01-11 06:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannedproducts',
            name='scanned_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 11, 6, 35, 53, 362771, tzinfo=utc)),
        ),
    ]
