# Generated by Django 4.0.1 on 2022-01-11 06:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_scannedproducts_scanned_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannedproducts',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.productdetails'),
        ),
        migrations.AlterField(
            model_name='scannedproducts',
            name='scanned_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 11, 6, 40, 43, 39866, tzinfo=utc)),
        ),
    ]
