# Generated by Django 4.0.1 on 2022-01-11 06:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_scannedproducts_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannedproducts',
            name='scanned_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
